// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI57m_RFf23VUnZDNeRkJWCcZSR9UxOLQ',
    appId: '1:91652984606:web:eb89fc40f7780da7c2030f',
    messagingSenderId: '91652984606',
    projectId: 'smart-gas-29e52',
    authDomain: 'smart-gas-29e52.firebaseapp.com',
    storageBucket: 'smart-gas-29e52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH3DSLnuKDNJxKDp3Z_UklLS0FjQ_b9Ug',
    appId: '1:91652984606:android:5f77f2171863482dc2030f',
    messagingSenderId: '91652984606',
    projectId: 'smart-gas-29e52',
    storageBucket: 'smart-gas-29e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANxNn_SAOUn99p7QrgDNkzJNCCpWQZxf8',
    appId: '1:91652984606:ios:3a9a8d9e824aaf1dc2030f',
    messagingSenderId: '91652984606',
    projectId: 'smart-gas-29e52',
    storageBucket: 'smart-gas-29e52.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANxNn_SAOUn99p7QrgDNkzJNCCpWQZxf8',
    appId: '1:91652984606:ios:3a9a8d9e824aaf1dc2030f',
    messagingSenderId: '91652984606',
    projectId: 'smart-gas-29e52',
    storageBucket: 'smart-gas-29e52.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI57m_RFf23VUnZDNeRkJWCcZSR9UxOLQ',
    appId: '1:91652984606:web:38e1cb3f62a6a28bc2030f',
    messagingSenderId: '91652984606',
    projectId: 'smart-gas-29e52',
    authDomain: 'smart-gas-29e52.firebaseapp.com',
    storageBucket: 'smart-gas-29e52.firebasestorage.app',
  );
}
